#!/bin/bash
#interactive -- demo of interactive input

read -p "Hello, what is your first name? " firstName
read -p "It is nice to meet you $firstName, what is your last name? " lastName
echo "*******************"
echo "$firstName $lastName, it's time to say good bye"
