#!/bin/bash

# Simple script to SSH through a bastion host/jumpserver to a target server.

# Global Variables
USERNAME=username
TARGETSERVER=target.server
JUMPSERVER=jump.server

ssh $USERNAME@$TARGETSERVER -o ProxyCommand="ssh -W %h:%p $USERNAME@$JUMPSERVER"