#!/bin/bash

# Simple script to SCP remote file through a jumpserver to the local host
# Setting SSH keys on each host is recommended

echo 'Remember to change the remote file path.'
echo 'Transferring file, default destination is the local desktop.'

USERNAME=username
TARGETSERVER=target.server
JUMPSERVER=jump.server
LOCALFOLDER=/path/to/local/folder
REMOTEFILE=/path/to/remote/file

ssh -o StrictHostKeyChecking=no -A -R 9999:localhost:22 $USERNAME@$JUMPSERVER "ssh -o StrictHostKeyChecking=no -A -R 9999:localhost:9999 $USERNAME@$TARGETSERVER scp -P 9999 $REMOTEFILE $USERNAME@localhost:$LOCALFOLDER"
